### ISSUE TITLE
Crash with mod installed 

### ISSUE THREAD

**Issue by MoonlightSystem** [stuin/SonicDevices#2]
This happens with your mod installed in my pack

[crash-2019-04-14_19.48.08-client.txt](https://github.com/stuin/SonicDevices/files/3078288/crash-2019-04-14_19.48.08-client.txt)

Mod list
![image](https://user-images.githubusercontent.com/8211402/56105435-12f9c980-5ef1-11e9-8c1b-eaf9bb8f10f5.png)

**Comment by stuin** [comment]
Alright Ill look at it. Looks like all dependencies are correct.

**Comment by stuin** [comment]
New version has been released.
