### ISSUE TITLE
[1.15.1] Crash on Server

### ISSUE THREAD

**Issue by Diamondman121314** [stuin/SonicDevices#3]
When using Sonic Devices on a server, it crashes.
https://gist.github.com/Diamondman121314/4b525e73b2bcd1ba7fbff246dcac8645

**Comment by stuin** [comment]
I have not tested if the error is completely fixed, but I think I know what happened and I think I fixed it. Please let me know If I am correct or not.

**Comment by Diamondman121314** [comment]
This did fix the issue, thank you!
